// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVXqQjvYe1_0dyz2xHRULOWQatobUA6qU',
    appId: '1:1049536531686:web:8729875faed4fbb6043f27',
    messagingSenderId: '1049536531686',
    projectId: 'mjsapp-2b237',
    authDomain: 'mjsapp-2b237.firebaseapp.com',
    storageBucket: 'mjsapp-2b237.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv_edI-eNXSS0rbVWpJPMfoxrK2JGfzH0',
    appId: '1:1049536531686:android:43fe39570f234322043f27',
    messagingSenderId: '1049536531686',
    projectId: 'mjsapp-2b237',
    storageBucket: 'mjsapp-2b237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsZkeL8CVBzLfEKB05fjj_4cTgTg2pLxE',
    appId: '1:1049536531686:ios:07f4e726b42c549d043f27',
    messagingSenderId: '1049536531686',
    projectId: 'mjsapp-2b237',
    storageBucket: 'mjsapp-2b237.appspot.com',
    iosBundleId: 'com.example.chequesManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsZkeL8CVBzLfEKB05fjj_4cTgTg2pLxE',
    appId: '1:1049536531686:ios:07f4e726b42c549d043f27',
    messagingSenderId: '1049536531686',
    projectId: 'mjsapp-2b237',
    storageBucket: 'mjsapp-2b237.appspot.com',
    iosBundleId: 'com.example.chequesManager',
  );
}
